name: student-performance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - plotly
  - pip:
      - ipykernel

# To activate this environment, use
#
#     $ conda activate student-performance
#
# To deactivate an active environment, use
#
#     $ conda deactivate
